trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: paycurra-core-iac-prd

steps:
- checkout: self
- script: |
    
    git clone https://pyc-strapi-cicd:AHroi2BUCiXaRMshWsniii0KF9muDS4Dpd1ZN852RpDpbUZwUnnJJQQJ99BFACAAAAArnTfkAAASAZDO47dr@dev.azure.com/Paycurra-HQ/paycurra/_git/paycurra-core-strapi
    cd paycurra-core-strapi
    git remote add github https://gastonbug:$(PYC.Strapi.GitHubToken)@github.com/gastonbug/paycurra-core-strapi.git
    git remote -v
    #git config pull.rebase true
    #git pull github master 
    git push github master --force
  displayName: 'Push to GitHub for Strapi Cloud'
