trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: paycurra-core-iac-prd

steps:
- checkout: self
- script: |
    git config --global user.email "oluseyi.adedokun@paycurra.com"
    git config --global user.name "gastonbug"
    git remote add github https://$(PYC.Strapi.GitHubToken)@github.com/gastonbug/paycurra-core-strapi.git
    git push github master
  displayName: 'Push to GitHub for Strapi Cloud'
