trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: paycurra-core-iac-prd

steps:
- checkout: self
- script: |
    git config --global user.email "oluseyi.adedokun@paycurra.com"
    git config --global user.name "gastonbug"
    git remote add github https://PYC.Strapi.GitHubToken@github.com/your-org/your-strapi-repo.git
    git push github main --force
  displayName: 'Push to GitHub for Strapi Cloud'
