trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- script: |
    git config --global user.email "ci@yourdomain.com"
    git config --global user.name "CI Bot"
    git remote add github https://<github_token>@github.com/your-org/your-strapi-repo.git
    git push github main --force
  displayName: 'Push to GitHub for Strapi Cloud'
